name: 'Create DMG'
description: 'Creates a DMG with a window layout and drag-to-Applications UI'

inputs:
  app_path:
    description: 'Path to the .app bundle to package'
    required: true
  dmg_output_path:
    description: 'Output path for the generated DMG file'
    required: true
  volname:
    description: 'Volume name for the DMG'
    required: false
    default: 'CopyShot'
  dmg_background_path:
    description: 'Path to the background image for the DMG'
    required: false
    default: '.github/actions/create-dmg/background.jpg'

runs:
  using: composite
  steps:
    - name: Install create-dmg
      shell: bash
      run: |
        brew install create-dmg

    - name: Stage app for DMG
      shell: bash
      run: |
        set -euo pipefail
        rm -rf dmg-stage
        mkdir -p dmg-stage
        cp -R "${{ inputs.app_path }}" "dmg-stage/CopyShot.app"
        ln -s /Applications "dmg-stage/Applications"
        
        # Copy background image if provided and exists
        if [ -f "${{ inputs.dmg_background_path }}" ]; then
            # Check image width to determine if it's Retina (@2x)
            WIDTH=$(sips -g pixelWidth "${{ inputs.dmg_background_path }}" | awk '/pixelWidth/ {print $2}')
            
            if [ "$WIDTH" -gt 700 ]; then
                echo "Detected high-resolution background ($WIDTH px width). Creating multi-resolution TIFF."
                
                # Create a temporary downscaled 1x version (700x500)
                sips -z 500 700 "${{ inputs.dmg_background_path }}" --out "dmg-stage/background_1x.jpg"
                
                # Combine original (2x) and downscaled (1x) into a multi-resolution TIFF
                # @2x image must be named with @2x for some tools, but tiffutil -cathidpi loves simple inputs
                tiffutil -cathidpicheck "dmg-stage/background_1x.jpg" "${{ inputs.dmg_background_path }}" -out "dmg-stage/background.tiff"
                
                echo "Created multi-resolution background.tiff"
            else
                echo "Detected standard-resolution background ($WIDTH px width). Using as-is."
                cp "${{ inputs.dmg_background_path }}" "dmg-stage/background.tiff"
            fi
        else
            echo "::warning::Background image not found at ${{ inputs.dmg_background_path }}. DMG will be created without custom background."
        fi

    - name: Create polished drag-to-Applications DMG
      shell: bash
      run: |
        set -euo pipefail

        # Ensure output directory exists
        mkdir -p "$(dirname "${{ inputs.dmg_output_path }}")"
        
        # Build create-dmg command args
        ARGS=(
          --volname "${{ inputs.volname }}"
          --window-pos 400 300
          --window-size 700 500
          --icon-size 140
          --icon "CopyShot.app" 180 225
          --icon "Applications" 520 225
          --hide-extension "CopyShot.app"
        )
        
        if [ -f "dmg-stage/background.tiff" ]; then
            ARGS+=(--background "dmg-stage/background.tiff")
        fi
        
        # Window and icon sizes/positions are in pixels.
        create-dmg \
          "${ARGS[@]}" \
          "${{ inputs.dmg_output_path }}" \
          "dmg-stage"
